services:

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:8080"   # ✅ FIX: host 5000 → container 8080
    depends_on:
      - mongo
    environment:
      - MONGO_CONN_STR=mongodb://mongo:27017/mydb

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
